name: learn_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0



dependencies:
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.2.1
  shared_preferences: ^2.5.3
  firebase_core: ^2.27.0
  flutter_slidable: ^2.0.0
  firebase_auth: ^4.17.4
  supabase_flutter: ^2.8.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.1
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
   - assets/logos/
   - assets/images/
   - assets/icons/
   - assets/images/onboarding/
   - .env

flutter_native_splash:
  color: '#000000'
  image: assets/logos/logo_white.png
  android: true
  ios: true
  web: false
  android_12:
    image: assets/logos/logo_white.png
    icon_background_color: '#000000'
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/img.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/img.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/img.png"